# Generated by Django 3.1.3 on 2020-12-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201201_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('men', 'Erkek'), ('women', 'Kadin'), ('unisex', 'UniSex')], default='unisex', max_length=6),
        ),
    ]
